export let allFoodItems = [
    {
        name: "Burger",
        details: [{
            code: "CL-BR-LR-#01",
            name: "Classic Burger (Large)",
            img: "/assets/images/burger/classic burger.jpg",
            par: "some text",
            price: 750.00,
            discount: 0,
            quantity: 10,
            expiredate: "",
            quantityId: "CL-BR-LR",
            addCartId: "btn-CL-BR-LR",
            functionName: "addClassicBurgerLarge"
        },
        {
            code: "CL-BR-R-#02",
            name: "Classic Burger (Regular)",
            img: "/assets/images/burger/large burger.jpg",
            par: "some text",
            price: 1500.00,
            discount: 0.15,
            quantity: 10,
            expiredate: "",
            quantityId: "CL-BR-R",
            addCartId: "btn-CL-BR-R",
            functionName: "addClassicBurgerRegular"
        },
        {
            code: "TU-BR-#03",
            name: "Turkey Burger",
            img: "/assets/images/burger/turkey burger.jpg",
            par: "some text",
            price: 1600.00,
            discount: 0,
            quantity: 10,
            expiredate: "",
            quantityId: "TU-BR",
            addCartId: "btn-TU-BR",
            functionName: "addTurkeyburger"
        },
        {
            code: "CHI-BR-LR-#04",
            name: "Chicken Burger (Large)",
            img: "/assets/images/burger/chicken burger large.jpg",
            par: "some text",
            price: 1400.00,
            discount: 0,
            quantity: 10,
            expiredate: "",
            quantityId: "CHI-BR-LR",
            addCartId: "btn-CHI-BR-LR",
            functionName: "addChickenBurgerLarge"
        },
        {
            code: "CHI-BR-R-#05",
            name: "Chicken Burger (Regular)",
            img: "/assets/images/burger/chicken burger regular.jpg",
            par: "some text",
            price: 800.00,
            discount: 0.2,
            quantity: 10,
            expiredate: "",
            quantityId: "CHI-BR-R",
            addCartId: "btn-CH-BR-R",
            functionName: "addChickenBurgerRegular"
        },
        {
            code: "CHE-BR-LR-#06",
            name: "Cheese Burger (Large)",
            img: "/assets/images/burger/cheese burger large.jpg",
            par: "some text",
            price: 1000.00,
            discount: 0,
            quantity: 10,
            expiredate: "",
            quantityId: "CHE-BR-LR",
            addCartId: "btn-CHE-BR-LR",
            functionName: "addCheeseBurgerLarge"
        },
        {
            code: "CHE-BR-R-#07",
            name: "Cheese Burger (Regular)",
            img: "/assets/images/burger/cheese burger regular.jpg",
            par: "some text",
            price: 600.00,
            discount: 0,
            quantity: 10,
            expiredate: "",
            quantityId: "CHE-BR-R",
            addCartId: "btn-CHE-BR-R",
            functionName: "addCheeseBurgerRegular"
        },
        {
            code: "BAC-BR-#08",
            name: "Bacon Burger",
            img: "/assets/images/burger/bacon burger.jpg",
            par: "some text",
            price: 650.00,
            discount: 0.15,
            quantity: 10,
            expiredate: "",
            quantityId: "BAC-BR",
            addCartId: "btn-BAC-BR",
            functionName: "addBaconBurger"
        },
        {
            code: "SH-BR-#09",
            name: "Shawarma Burger",
            img: "/assets/images/burger/shawarma burger.jpg",
            par: "some text",
            price: 800.00,
            discount: 0,
            quantity: 10,
            expiredate: "",
            quantityId: "SH-BR",
            addCartId: "btn-SH-BR",
            functionName: "addShawarmaBurger"
        },
        {
            code: "OL-BR-#10",
            name: "Olive Burger",
            img: "/assets/images/burger/olive burger.jpg",
            par: "some text",
            price: 1800.00,
            discount: 0,
            quantity: 10,
            expiredate: "",
            quantityId: "OL-BR",
            addCartId: "btn-OL-BR",
            functionName: "addOliveBurger"
        },
        {
            code: "CHE-BR-DB-#11",
            name: "Double-Cheese Burger",
            img: "/assets/images/burger/double cheese burger.jpg",
            par: "some text",
            price: 1250.00,
            discount: 0.2,
            quantity: 10,
            expiredate: "",
            quantityId: "CHE-BR-DB",
            addCartId: "btn-CHE-BR-DB",
            functionName: "addCheeseBurgerDouble"
        },
        {
            code: "CR-BR-R-#12",
            name: "Crispy Chicken Burger (Regular)",
            img: "/assets/images/burger/crispy chicken burger regular.jpg",
            par: "some text",
            price: 1200.00,
            discount: 0,
            quantity: 10,
            expiredate: "",
            quantityId: "CR-BR-R",
            addCartId: "btn-CR-BR-R",
            functionName: "addChickenBurgerCrispyRegular"
        },
        {
            code: "CR-BR-LR-#13",
            name: "Crispy Chicken Burger (Large)",
            img: "/assets/images/burger/crispy chicken burger large.jpg",
            par: "some text",
            price: 1600.00,
            discount: 0.1,
            quantity: 10,
            expiredate: "",
            quantityId: "CR-BR-LR",
            addCartId: "btn-CR-BR-LR",
            functionName: "addChickenBurgerCrispyLarge"
        },
        {
            code: "PN-BR-#14",
            name: "Paneer Burger",
            img: "/assets/images/burger/paneer burger.jpg",
            par: "some text",
            price: 900.00,
            discount: 0,
            quantity: 10,
            expiredate: "",
            quantityId: "PN-BR",
            addCartId: "btn-PN-BR",
            functionName: "addPaneerBurger"
        },
        ]
    },
    {
        name: "Submarine",
        details: [{
            code: "CH-SB-CR-LR-#01",
            name: "Crispy Chicken Submarine (Large)",
            img: "/assets/images/submarine/submarine.jpg",
            par: "some text",
            price: 2000.00,
            discount: 0,
            quantity: 10,
            expiredate: "",
            quantityId: "CH-SB-CR-LR",
            addCartId: "btn-CH-SB-CR-LR",
            functionName: "addCrispyChickenSubLarge"
        },
        {
            code: "CH-SB-CR-R-#02",
            name: "Crispy Chicken Submarine (Regular)",
            img: "/assets/images/submarine/submarine.jpg",
            par: "some text",
            price: 1500.00,
            discount: 0,
            quantity: 10,
            expiredate: "",
            quantityId: "CH-SB-CR-R",
            addCartId: "btn-CH-SB-CR-R",
            functionName: "addCrispyChickenSubRegular"
        },
        {
            code: "CH-SB-LR-#03",
            name: "Chicken Submarine (Large)",
            img: "/assets/images/submarine/submarine.jpg",
            par: "some text",
            price: 1800.00,
            discount: 0.03,
            quantity: 10,
            quantityId: "CH-SB-LR",
            addCartId: "btn-CH-SB-LR",
            functionName: "addChickenSubLarge"
        },
        {
            code: "CH-SB-R-#04",
            name: "Chicken Submarine (Regular)",
            img: "/assets/images/submarine/submarine.jpg",
            par: "some text",
            price: 1400.00,
            discount: 0,
            quantity: 10,
            expiredate: "",
            quantityId: "CH-SB-R",
            addCartId: "btn-CH-SB-R",
            functionName: "addChickenSubRegular"
        },
        {
            code: "GR-SB-#05",
            name: "Grinder Submarine",
            img: "/assets/images/submarine/submarine.jpg",
            par: "some text",
            price: 2300.00,
            discount: 0,
            quantity: 10,
            expiredate: "",
            quantityId: "GR-SB",
            addCartId: "btn-GR-SB",
            functionName: "addGrinderSub"
        },
        {
            code: "CHE-SB-#06",
            name: "Cheese Submarine",
            img: "/assets/images/submarine/submarine.jpg",
            par: "some text",
            price: 2200.00,
            discount: 0,
            quantity: 10,
            expiredate: "",
            quantityId: "CHE-SB",
            addCartId: "btn-CHE-SB",
            functionName: "addCheeseSub"
        },
        {
            code: "CHE-CH-SB-DB-#07",
            name: "Double Cheese n Chicken Submarine",
            img: "/assets/images/submarine/submarine.jpg",
            par: "some text",
            price: 1900.00,
            discount: 0.16,
            quantity: 10,
            expiredate: "",
            quantityId: "CHE-CH-SB-DB",
            addCartId: "btn-CHE-CH-SB-DB",
            functionName: "addDoubleCheeseChickenSub"
        },
        {
            code: "SP-SB-HG-#08",
            name: "Special Horgie Submarine",
            img: "/assets/images/submarine/submarine.jpg",
            par: "some text",
            price: 2800.00,
            discount: 0,
            quantity: 10,
            expiredate: "",
            quantityId: "SP-SB-HG",
            addCartId: "btn-SP-SB-HG",
            functionName: "addSpecialHorgieSub"
        },
        {
            code: "MS-SP-SB-#09",
            name: "MOS Special Submarine",
            img: "/assets/images/submarine/submarine.jpg",
            par: "some text",
            price: 3000.00,
            discount: 0,
            quantity: 10,
            expiredate: "",
            quantityId: "MS-SP-SB",
            addCartId: "btn-MS-SP-SB",
            functionName: "addMosSpecialSub"
        },
        ]
    },
    {
        name: "Fries",
        details: [{
            code: "ST-FR-LR-#01",
            name: "Steak Fries (Large)",
            img: "/assets/images/fries/fries.jpg",
            par: "some text",
            price: 1200.00,
            discount: 0,
            quantity: 10,
            expiredate: "",
            quantityId: "ST-FR-LR",
            addCartId: "btn-ST-FR-LR",
            functionName: "addSteakFriesLarge"
        },
        {
            code: "ST-FR-MD-#02",
            name: "Steak Fries (Medium)",
            img: "/assets/images/fries/fries.jpg",
            par: "some text",
            price: 600.00,
            discount: 0,
            quantity: 10,
            expiredate: "",
            quantityId: "ST-FR-MD",
            addCartId: "btn-ST-FR-MD",
            functionName: "addSteakFriesMedium"
        },
        {
            code: "FE-FR-LR-#03",
            name: "French Fries (Large)",
            img: "/assets/images/fries/fries.jpg",
            par: "some text",
            price: 800.00,
            discount: 0,
            quantity: 10,
            expiredate: "",
            quantityId: "FE-FR-LR",
            addCartId: "btn-FE-FR-LR",
            functionName: "addFrenchFriesLarge"
        },
        {
            code: "FE-FR-MD-#04",
            name: "French Fries (Medium)",
            img: "/assets/images/fries/fries.jpg",
            par: "some text",
            price: 650.00,
            discount: 0,
            quantity: 10,
            expiredate: "",
            quantityId: "FE-FR-MD",
            addCartId: "btn-FE-FR-MD",
            functionName: "addFrenchFriesMedium"
        },
        {
            code: "FE-FR-SM-#05",
            name: "French Fries (Small)",
            img: "/assets/images/fries/fries.jpg",
            par: "some text",
            price: 450.00,
            discount: 0,
            quantity: 10,
            expiredate: "",
            quantityId: "FE-FR-SM",
            addCartId: "btn-FE-FR-SM",
            functionName: "addFrenchFriesSmall"
        },
        {
            code: "SW-PT-FR-LR-#06",
            name: "Sweet Potato Fries (Large)",
            img: "/assets/images/fries/fries.jpg",
            par: "some text",
            price: 600.00,
            discount: 0,
            quantity: 10,
            expiredate: "",
            quantityId: "SW-PT-FR-LR",
            addCartId: "btn-SW-PT-FR-LR",
            functionName: "addSweetPotatoFriesLarge"
        }
        ]
    },
    {
        name: "Pasta",
        details: [{
            code: "CHE-CH-PS-#01",
            name: "Chicken n Cheese Pasta",
            img: "/assets/images/pasta/pasta.jpg",
            par: "some text",
            price: 1600.00,
            discount: 0.15,
            quantity: 10,
            expiredate: "",
            quantityId: "CHE-CH-PS",
            addCartId: "btn-CHE-CH-PS",
            functionName: "addChickenCheesePasta"
        },
        {
            code: "CH-PS-PN-#02",
            name: "Chicken Penne Pasta",
            img: "/assets/images/pasta/pasta.jpg",
            par: "some text",
            price: 1700.00,
            discount: 0,
            quantity: 10,
            expiredate: "",
            quantityId: "CH-PS-PN",
            addCartId: "btn-CH-PS-PN",
            functionName: "addChickenPenePasta"
        },
        {
            code: "TU-PS-#03",
            name: "Ground Turkey Pasta Bake",
            img: "/assets/images/pasta/pasta.jpg",
            par: "some text",
            price: 2900.00,
            discount: 0.1,
            quantity: 10,
            expiredate: "",
            quantityId: "TU-PS",
            addCartId: "btn-TU-PS",
            functionName: "addTurkeyPasta"
        },
        {
            code: "CR-PS-#04",
            name: "Creamy Shrimp Pasta",
            img: "/assets/images/pasta/pasta.jpg",
            par: "some text",
            price: 2000.00,
            discount: 0,
            quantity: 10,
            expiredate: "",
            quantityId: "CR-PS",
            addCartId: "btn-CR-PS",
            functionName: "addCreamyPasta"
        },
        {
            code: "LM-PS-#05",
            name: "Lemon Butter Pasta",
            img: "/assets/images/pasta/pasta.jpg",
            par: "some text",
            price: 1950.00,
            discount: 0,
            quantity: 10,
            expiredate: "",
            quantityId: "LM-PS",
            addCartId: "btn-LM-PS",
            functionName: "addLemonPasta"
        },
        {
            code: "TN-PS-#06",
            name: "Tagliatelle Pasta",
            img: "/assets/images/pasta/pasta.jpg",
            par: "some text",
            price: 2400.00,
            discount: 0.01,
            quantity: 10,
            expiredate: "",
            quantityId: "TN-PS",
            addCartId: "btn-TN-PS",
            functionName: "addTangilatePasta"
        },
        {
            code: "BK-PS-RV-#07",
            name: "Baked Ravioli",
            img: "/assets/images/pasta/pasta.jpg",
            par: "some text",
            price: 2000.00,
            discount: 0.01,
            quantity: 10,
            quantityId: "BK-PS-RV",
            addCartId: "btn-BK-PS-RV",
            functionName: "addBakedRavioli"
        }
        ]
    },
    {
        name: "Chicken",
        details: [{
            code: "FR-CH-SM-#01",
            name: "Fried Chicken (Small)",
            img: "/assets/images/chicken/chicken.jpg",
            par: "some text",
            price: 1200.00,
            discount: 0,
            quantity: 10,
            expiredate: "",
            quantityId: "FR-CH-SM",
            addCartId: "btn-FR-CH-SM",
            functionName: "addFriedChickenSmall"
        },
        {
            code: "FR-CH-R-#02",
            name: "Fried Chicken (Regular)",
            img: "/assets/images/chicken/chicken.jpg",
            par: "some text",
            price: 2300.00,
            discount: 0.1,
            quantity: 10,
            expiredate: "",
            quantityId: "FR-CH-R",
            addCartId: "btn-FR-CH-R",
            functionName: "addFriedChickenRegular"
        },
        {
            code: "FR-CH-LR-#03",
            name: "Fried Chicken (Large)",
            img: "/assets/images/chicken/chicken.jpg",
            par: "some text",
            price: 3100.00,
            discount: 0.05,
            quantity: 10,
            expiredate: "",
            quantityId: "FR-CH-LR",
            addCartId: "btn-FR-CH-LR",
            functionName: "addFriedChickenLarge"
        },
        {
            code: "HT-WG-LR-#04",
            name: "Hot Wings (Large)",
            img: "/assets/images/chicken/chicken.jpg",
            par: "some text",
            price: 2400.00,
            discount: 0,
            quantity: 10,
            expiredate: "",
            quantityId: "HT-WG-LR",
            addCartId: "btn-HT-WG-LR",
            functionName: "addHotWingsLarge"
        },
        {
            code: "DV-CH-LR-#05",
            name: "Devilled Chicken (Large)",
            img: "/assets/images/chicken/chicken.jpg",
            par: "some text",
            price: 900.00,
            discount: 0,
            quantity: 10,
            expiredate: "",
            quantityId: "DV-CH-LR",
            addCartId: "btn-DV-CH-LR",
            functionName: "addDevilledChickenLarge"
        },
        {
            code: "BB-CH-R-#06",
            name: "BBQ Chicken (Regular)",
            img: "/assets/images/chicken/chicken.jpg",
            par: "some text",
            price: 2100.00,
            discount: 0,
            quantity: 10,
            expiredate: "",
            quantityId: "BB-CH-R",
            addCartId: "btn-BB-CH-R",
            functionName: "addBbqChickenRegular"
        }
        ]
    },
    {
        name: "Beverages",
        details: [{
            code: "PP-BV-#01",
            name: "Pepsi (330ml)",
            img: "/assets/images/beverages/beverages.jpg",
            par: "some text",
            price: 990.00,
            discount: 0.05,
            quantity: 10,
            expiredate: "2025-07-09",
            quantityId: "PP-BV",
            addCartId: "btn-PP-BV",
            functionName: "addPepsi"
        },
        {
            code: "CC-BV-#02",
            name: "Coca-Cola (330ml)",
            img: "/assets/images/beverages/beverages.jpg",
            par: "some text",
            price: 1230.00,
            discount: 0,
            quantity: 10,
            expiredate: "2025-07-09",
            quantityId: "CC-BV",
            addCartId: "btn-CC-BV",
            functionName: "addCocaCola"
        },
        {
            code: "SP-BV-#03",
            name: "Sprite (330ml)",
            img: "/assets/images/beverages/beverages.jpg",
            par: "some text",
            price: 1500.00,
            discount: 0.03,
            quantity: 10,
            expiredate: "2025-07-09",
            quantityId: "SP-BV",
            addCartId: "btn-SP-BV",
            functionName: "addSpriter"
        },
        {
            code: "MR-BV-#04",
            name: "Mirinda (330ml)",
            img: "/assets/images/beverages/beverages.jpg",
            par: "some text",
            price: 850.00,
            discount: 0.07,
            quantity: 10,
            expiredate: "2025-07-09",
            quantityId: "MR-BV",
            addCartId: "btn-MR-BV",
            functionName: "addMiranda"
        }
        ]
    }
];